const FETCH_USER_DETAILS = 'FETCH_USER_DETAILS';
const LOGOUT = 'LOGOUT';
const LOGIN = 'LOGIN';
const FETCH_SINGLE_SUCCESS = 'FETCH_SINGLE_SUCCESS';
const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR';
const REMOVE_FAV = 'REMOVE_FAV';
const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
const ADD_DOCTOR = 'ADD_DOCTOR';
const FETCH_SINGLE_PENDING = 'FETCH_SINGLE_PENDING';
const LOGIN_USER_PENDING = 'LOGIN_USER_PENDING';
const FETCH_APPOINTMENTS_PENDING = 'FETCH_APPOINTMENTS_PENDING';
const CREATE_ITEM_PENDING = 'CREATE_ITEM_PENDING';

export {
  FETCH_PRODUCTS_ERROR,
  FETCH_APPOINTMENTS_PENDING,
  FETCH_SINGLE_SUCCESS,
  FETCH_PRODUCTS_SUCCESS,
  FETCH_USER_DETAILS,
  CREATE_ITEM_PENDING,
  REMOVE_FAV,
  ADD_DOCTOR,
  LOGIN,
  LOGOUT,
  FETCH_SINGLE_PENDING,
  LOGIN_USER_PENDING,
};